import { type SearchItem } from "./types";

export const data: SearchItem[] = [

  {
    id: "p1",
    type: "person",
    name: "Randall Johnson",
    photoUrl: "/avatars/randall.jpg",
    status: "active",
    lastActive: "now",
  },
  {
    id: "p2",
    type: "person",
    name: "Kristinge Karand",
    photoUrl: "/avatars/kristinge.jpg",
    status: "inactive",
    lastActive: "2d ago",
  },
  {
    id: "p3",
    type: "person",
    name: "Caroline Dribsson",
    photoUrl: "/avatars/caroline.jpg",
    status: "unactivated",
    lastActive: "3d ago",
  },
  {
    id: "p4",
    type: "person",
    name: "Adam Cadribean",
    photoUrl: "/avatars/adam.jpg",
    status: "active",
    lastActive: "1w ago",
  },
  {
    id: "p5",
    type: "person",
    name: "Margaret Cendribbgson",
    photoUrl: "/avatars/margaret.jpg",
    status: "inactive",
    lastActive: "2w ago",
  },

  {
    id: "f1",
    type: "folder",
    name: "Random Michael Folder",
    fileCount: 12,
    path: "Photos",
    edited: "12m ago",
  },
  {
    id: "f2",
    type: "folder",
    name: "Dribble Project",
    fileCount: 8,
    path: "Projects",
    edited: "2m ago",
  },
  {
    id: "f3",
    type: "folder",
    name: "Karand Work Docs",
    fileCount: 24,
    path: "Documents",
    edited: "5h ago",
  },

  {
    id: "file1",
    type: "file",
    name: "creative_file_frandkies.jpg",
    fileType: "other",
    path: "Photos",
    edited: "15m ago",
    actions: ["open", "copy"],
  },
  {
    id: "file2",
    type: "file",
    name: "final_dribble_presentation.pptx",
    fileType: "presentation",
    path: "Presentations",
    edited: "1w ago",
  },
  {
    id: "file3",
    type: "file",
    name: "rand_notes_project.docx",
    fileType: "doc",
    path: "Work/Notes",
    edited: "3d ago",
  },
  {
    id: "file4",
    type: "file",
    name: "budget_karand.xlsx",
    fileType: "spreadsheet",
    path: "Finance",
    edited: "1m ago",
  },
  {
    id: "file5",
    type: "file",
    name: "meeting_dribble_summary.pdf",
    fileType: "pdf",
    path: "Meetings",
    edited: "2w ago",
  },

  {
    id: "v1",
    type: "video",
    name: "files_karand_video.avi",
    path: "Videos",
    added: "12m ago",
  },
  {
    id: "v2",
    type: "video",
    name: "dribble_animation.avi",
    path: "Videos",
    added: "1y ago",
  },
  {
    id: "v3",
    type: "video",
    name: "rand_team_call.mp4",
    path: "Calls",
    added: "3d ago",
  },

  {
    id: "img1",
    type: "image",
    name: "sunset_rand.jpg",
    imageUrl: "/images/sunset.jpg",
    path: "Photos/Nature",
    edited: "5h ago",
    resolution: "1920x1080",
  },
  {
    id: "img2",
    type: "image",
    name: "team_dribble.png",
    imageUrl: "/images/team.png",
    path: "Work/Events",
    edited: "2d ago",
    resolution: "1200x800",
  },
  {
    id: "img3",
    type: "image",
    name: "logo_karand_design.svg",
    imageUrl: "/images/logo.svg",
    path: "Design/Logos",
    edited: "1w ago",
  },
  {
    id: "img4",
    type: "image",
    name: "project_rand_flowchart.png",
    imageUrl: "/images/flowchart.png",
    path: "Projects/Flows",
    edited: "4h ago",
    resolution: "1024x768",
  },
];
